apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\fhaze\bin\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sandbox
  name: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sandbox
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\fhaze\bin\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sandbox
    spec:
      containers:
      - image: fhaze/sandbox:1.0
        imagePullPolicy: ""
        name: sandbox
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\fhaze\bin\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sandbox
  name: sandbox
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: sandbox
  type: LoadBalancer
status:
  loadBalancer: {}
