apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox
    version: v1
  name: sandbox-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
      version: v1
  template:
    metadata:
      labels:
        app: sandbox
        version: v1
    spec:
      containers:
      - image: fhaze/sandbox:1.0
        name: sandbox
        ports:
        - containerPort: 8080
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sandbox
    service: sandbox
  name: sandbox
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: sandbox
